{% set name = "pykmip" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/PyKMIP-{{ version }}.tar.gz
  sha256: bb6ff310bba8b1130ffe675347f668f7234d022ba3d51edea5ea7e2ea9523897

build:
  entry_points:
    - pykmip-server = kmip.services.server.server:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - cryptography
    - enum-compat
    - python >={{ python_min }}
    - requests
    - six
    - sqlalchemy

test:
  imports:
    - kmip
  commands:
    - pip check
    - pykmip-server --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/OpenKMIP/PyKMIP
  summary: KMIP library
  license: Apache-2.0
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
