schema_version: 1

context:
  name: pykmip
  version: "0.11.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: eb42e2d9674e470935d98474b8502e675894cc8489362d8419fdd957319f2b3e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - pykmip-server = kmip.services.server.server:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - cryptography
    - enum-compat
    - python >=${{ python_min }}
    - requests
    - six
    - sqlalchemy

tests:
  - python:
      imports:
        - kmip
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pykmip-server --help

about:
  summary: KMIP library
  license: Apache-2.0
  license_file:
    - LICENSE.txt
  homepage: https://github.com/OpenKMIP/PyKMIP

extra:
  recipe-maintainers:
    - jan-janssen
